import {
  Dashboard,
  Group,
  Person,
  AdminPanelSettings,
  VpnKey,
  MoveToInbox,
  Outbox,
  Autorenew,
  FolderOpen,
  Folder,
  ReceiptLong,
  RequestQuote,
  Warehouse,
  Checklist,
  Book,
  MedicalServices,
  LocalPharmacy,
  Source,
  PersonSearch,
  PointOfSale,
  Assignment,
  FactCheck,
  Feedback,
  Category,
  LocalHospital,
  PaymentSharp,
  CardGiftcard,
  Science,
  DiamondSharp,
  DiamondRounded,
  Medication,
  IntegrationInstructions,
  ReportProblem,
  Settings,
  InfoRounded,
  GppGood,
  AddBusiness,
  ShoppingCart,
  CalendarToday,
  Badge,
  Undo,
  QrCode2,
  ReceiptOutlined,
  InsertChart,
  AccountBalanceWallet,
  CleaningServices,
  DeviceThermostat,
  Inventory,
  CardMembership,
  Summarize,
  AccountBalance,
  ListAlt,
  ShowChart,
  AccessTime,
  BarChart,
  Star,
  Discount,
  InsightsOutlined,
  Factory,
  Store,
  SupervisedUserCircle,
  Inventory2,
  NoteAlt,
  Newspaper,
  WorkspacePremium,
} from "@mui/icons-material";
import { ISidebarMenu } from "../interfaces/sidebar";
import { PATH_NAME } from "./path";
import locales from "../locales";
import { Permission } from "../enums/common";
import { 
  PermissionAccess, 
  PermissionCashBook,
  PermissionCategory, 
  PermissionCustomer, 
  PermissionCustomerComplaint, 
  PermissionDrugQualityPeriods, 
  PermissionDrugSideEffectTrackings, 
  PermissionEmployeeCommission, 
  PermissionExcessStockReports, 
  PermissionHygieneReports, 
  PermissionInboundHistories, 
  PermissionInboundOrders, 
  PermissionIngredient, 
  PermissionInventoryChecks, 
  PermissionManufacturer, 
  PermissionMedicalFacilities, 
  PermissionNews, 
  PermissionOpeningInventory, 
  PermissionPaymentMethod, 
  PermissionPaymentVoucher, 
  PermissionPointConversion, 
  PermissionPrescriptions, 
  PermissionProductGroups, 
  PermissionProductInventoryHistories, 
  PermissionProductRevenueReport, 
  PermissionProducts, 
  PermissionPromotion, 
  PermissionRecalledSuspendedDrugs, 
  PermissionReceipt, 
  PermissionReturnOrders, 
  PermissionReturnSuppliers, 
  PermissionRevenueReports, 
  PermissionSaleReceipts, 
  PermissionSaleShift, 
  PermissionStorageConditionReports, 
  PermissionSupplier, 
  PermissionTransactionHistories, 
  PermissionUnits,
  PermissionMember,
  PermissionPharmacyGroups,
  PermissionDebitReports,
  PermissionProfitReports,
  PermissionOutOfStockReport,
  PermissionBusinessSummaryReport,
  PermissionLoyaltyPointReport,
  PermissionMedicineInboundLogbook,
  PermissionCustomerTrackingBook,
  PermissionPrescriptionMedicineBook,
  PermissionPatientTrackingBook,
  PermissionSpecialMedicineTracking,
  PermissionTrackingBuySpecialMedicine,
} from "../enums/permission";

const {sidebar: tSidebar} = locales['vi']

export const menuConfig: ISidebarMenu = [
  {
    label: tSidebar.account,
    icon: Group,
    permission: Permission.Owner,
    key: "userManagement",
    children: [
      { label: tSidebar.user, icon: Person, path: PATH_NAME.user },
      { label: tSidebar.groups, icon: AdminPanelSettings, path: PATH_NAME.groups },
      { label: tSidebar.permission, icon: VpnKey, path: PATH_NAME.permission },
    ],
  },
];
